version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db-guessgame
    environment:
      - POSTGRES_DB=guessdb
      - POSTGRES_USER=guessgame-user
      - POSTGRES_PASSWORD=rrp7OZV087T48V
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure

  backend1:
    container_name: backend1-guessgame
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=run.py
      - FLASK_DB_TYPE=postgres
      - FLASK_DB_USER=guessgame-user
      - FLASK_DB_NAME=guessdb
      - FLASK_DB_PASSWORD=rrp7OZV087T48V
      - FLASK_DB_HOST=db
      - FLASK_DB_PORT=5432
    restart: on-failure
    expose:
      - "5000"
    depends_on:
      - postgres

  backend2:
    container_name: backend2-guessgame
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=run.py
      - FLASK_DB_TYPE=postgres
      - FLASK_DB_USER=guessgame-user
      - FLASK_DB_NAME=guessdb
      - FLASK_DB_PASSWORD=rrp7OZV087T48V
      - FLASK_DB_HOST=db
      - FLASK_DB_PORT=5432
    restart: on-failure
    expose:
      - "5000"
    depends_on:
      - postgres

  frontend:
    container_name: frontend-guessgame
    ports:
      - "8080:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure


volumes:
  postgres-data:
